---
version: "3"
services:

  mqtt-server:
    image: eclipse-mosquitto:1.4.12
    restart: always
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/certs/:/etc/mosquitto/certs/
    ports:
      - '1883:1883'
      - '8883:8883'
      - '1884:1884'
      - '8884:8884'

  hulaaki:
    build: .
    command: mix test
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/deps
    depends_on:
      - mqtt-server
    environment:
      MQTT_HOST: mqtt-server
      MQTT_PORT: 1883
      MQTT_WS_PORT: 1884
      MQTT_TLS_PORT: 8883
      MQTT_WS_TLS_PORT: 8884
